name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the deployment on push to the 'main' branch (or 'master' if that's your default branch)

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use the desired version of Node.js

      - name: Install dependencies
        run: |
          npm install  # Install project dependencies

      - name: Build and Export Next.js
        run: |
          npm run build  # Build the Next.js app

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.1.3  # Use the correct version
        with:
          branch: gh-pages  # Specify the 'gh-pages' branch for deployment
          folder: out  # Folder that contains the static files (output from 'npm run export')
          clean: true  # Clean the gh-pages branch before deploying (optional but recommended)
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token to authenticate the deployment
