name: Deploy Next.js app to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you're deploying from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # GitHub Pages branch
          folder: out       # Output folder for static files (Next.js default)
          clean: true       # Remove old files before deploying
